import Head from "next/head";
import Link from "next/link";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: "flex", flexDirection: "column" }}>
          <Link href="/hello">移動する</Link>
          <Link href="/autocomplete">auto completeに移動する</Link>
          <Link href="/datefield">date fieldに移動する</Link>
        </Box>
      </main>
    </>
  );
}
